name: c-labs
on:
  push:
    branches: [ master ]

jobs:

  lab5:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: Build
      run: make build
      working-directory: ./lab5/
    - name: Run(Test input) + Memcheck
      run: make memcheck
      working-directory: ./lab5/
    - name: Clean
      run: make clean
      working-directory: ./lab5/
      
lab6:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: Build
      run: make build
      working-directory: ./lab6/
    - name: Run(Test input) + Memcheck
      run: make memcheck
      working-directory: ./lab6/
    - name: Clean
      run: make clean
      working-directory: ./lab6/
      
lab7:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build
      working-directory: ./lab7/
    - name: Clean
      run: make clean
      working-directory: ./lab7/

      
